spring.application.name=web-ems

## データベースへの接続情報
spring.datasource.url=jdbc:mysql://localhost:3306/EMS
spring.datasource.username=app-user
spring.datasource.password=Kr0n0SEMs
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

## Mapper.xmlの配置場所
mybatis.mapper-locations=classpath:mapper/*.xml
